### ISSUE TITLE
video

### ISSUE THREAD

**Issue by louslife6788** [learn-co-curriculum/oo-ruby-video-review-music-library-cli#4]
the video link does not work and is defiantly necessary

**Comment by ihollander** [comment]
Hi @louslife6788 - thanks for flagging this! This video was recorded by an instructor who is no longer with Flatiron and was subsequently removed from YouTube so it's unfortunately no longer available. Here is another instructor's walkthrough in case this is helpful: https://www.youtube.com/watch?v=E31klAW-ZoM
