### ISSUE TITLE
(!) This video is unavailable

### ISSUE THREAD

**Issue by sopharsogood** [learn-co-curriculum/oo-ruby-video-review-music-library-cli#5]
The video is unavailable and just displays a black rectangle with:

(!) This video is unavailable

**Comment by ihollander** [comment]
Hi @sopharsogood - thanks for flagging this! This video was recorded by an instructor who is no longer with Flatiron and was subsequently removed from YouTube so it's unfortunately no longer available. Here is another instructor's walkthrough in case this is helpful: https://www.youtube.com/watch?v=E31klAW-ZoM
